**####---------------------------------------- Assessment-02 ----------------------------------------####**

------------------------------------------------------------------------------------------------------------------------------
**####-------------------------------------- Section A – Interview Theory ---------------------------------------####**

**# ================================================ Q.1 ================================================ #**
**Q1.** What's the difference between a Series and a DataFrame? Give one operation that works on both, and one that works only on a DataFrame.

**Ans :**
1.   Series is one dimensional data structure in pandas, while DataFrame is two dimensional.
2.   Series store data in single column, while DataFrame stores data in multiple rows and columns.
3.   head() works on both, but columns works only on dataframe.   
-------------------------------------------------------------------------------------------------------------------------

**# ================================================ Q.2 ================================================ #**

**Q2.** What does inplace=True do? Why is the pandas team discouraging its use in newer versions? Give one example where you'd avoid it.

**Ans:**
1.  inplace=True changes the existing data directly rather than creating new dataframe.
2.  Because it don't improve performance every time and makes code less predictable.
3.  Example : Suppose I remove the Gender column using df.drop("Gender", inplace=True). Later, if it is needed again, I cannot get it back because the original DataFrame has already been modified.
-----------------------------------------------------------------------------------------------------------------------

**# ================================================ Q.3 ================================================ #**

**Q3.** Explain the difference between .fillna() and .dropna(). When would a data analyst pick one over the other? Be specific - give a concrete situation for each.

**Ans:**

1.  .fillna() is used to fill the missing values with mean/median/unknown or any other specified values.
2.  .dropna() is used to remove the rows or columns with null values when they are not useful for analysis.
3.  .fillna() Example:   If a customer's Age is missing but the remaining details are available, use .fillna() to fill the missing value (e.g., "Unknown").
.dropna() Example:   If a customer's Name, Contact, and other important details are missing, the row is not useful for analysis, so use .dropna() to remove it.
-------------------------------------------------------------------------------------------------------------------------

**# ================================================ Q.4 ================================================ #**

**Q4.** What does pd.to_numeric(col, errors='coerce') do that plain pd.to_numeric(col) does NOT? Which one would you use on real-world messy data, and why?

**Ans:**
1.   It don't gives error, it converts invalid values into NaN.
2.   I would use pd.to_numeric(col, errors='coerce'), because it can clean and handle large messy data in real world without giving errors.
------------------------------------------------------------------------------------------------------------------------

**# ================================================ Q.5 ================================================ #**

**Q5.** Explain .loc vs .iloc with one example each. Then describe a case where df.loc[0] and df.iloc[0] return different rows.

**Ans:**
1.   .loc is label-based indexing, while .iloc is integer-based.
2.   df.loc[1:3] give output of row 1 to 3 all, while .iloc[1:3] will give rows at position 1 and 2 only, not 3.
3.   df.loc[0] only works when lables are like [0,1,2,3...] but if lables are like [1001,1002,1003,..] then df.loc[0] will throw error, while df.iloc[0] still returns the first row.
-------------------------------------------------------------------------------------------------------------------------

**# ================================================ Q.6 ================================================ #**
**Q6.** What is the difference between .map(), .apply(), and .replace() for a Series? When would you reach for each?

**Ans:**
1.   I would use .map() to map one value with another using dictionary or function.
2.   I would use .apply() to apply custom function to each value in series.
3.   I would use .replace() one or more existing values with new values.
4.   .map() for mapping values, .apply() for caulculations and .replace() for simple replacement of values.
-------------------------------------------------------------------------------------------------------------------------

**# ================================================ Q.7 ================================================ #**

**Q7.** What is the SettingWithCopyWarning? Give one example of code that triggers it and one way to fix it. (Hint: the chained-assignment pattern.)

**Ans:**
1.   SettingWithCopyWarning is shown when Pandas is not sure whether original data is modified or copy of it.
2.   It happens due to chained assignment like....
new_df = df[df["Salary"] > 80000],                            
new_df["Salary"] = 10000
3.   It can be fixed using .loc[]
-------------------------------------------------------------------------------------------------------------------------

**# ================================================ Q.8 ================================================ #**

**Q8.** Explain pd.cut() vs pd.qcut(). If you have annual income data and want to label customers as Low / Mid / High earners, which one fits better? Why

**Ans:**
1.   pd.cut() has fixed value range, while pd.qcut() has equal number of values in each range.
2.   Suppose, salary data is..., [10k, 22k, 30k, 45k, 51k, 63k]
3.   Ex : pd.cut with range (0-20k, 21k-40k, 41k-70k) as Low, Mid and High
Then..,  (Low-> 10k), (Mid-> 22k, 30k), (High-> 45k, 51k, 63k)
4.   Ex : pd.qcut will have 3 records with equal number like..
[10k, 22k],
[30k, 45k],
[51k, 63k]
-------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------
**####-------------------------------------- Section B – Predict the Output  ---------------------------------------####**

**# ================================================ Q.9 ================================================ #**

In [ ]:
# Q9. Predict the output. What's in df at the end?

# Output - a:[10, 20, 30], b:[4, 5, 6]
# Because df and df2 are both same objects

import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
df2 = df
df2['a'] = [10, 20, 30]
print(df)

    a  b
0  10  4
1  20  5
2  30  6

**# =============================================== Q.10 =============================================== #**

In [ ]:
# Q10. Predict both outputs.

# Output - mean= 3, sum= 12
# np.nan means the value is missing, so mean() and sum() will ignore it.

import pandas as pd
import numpy as np
s = pd.Series([1, 2, np.nan, 4, 5])
print(s.mean())
print(s.sum())

3.0
12.0

**# =============================================== Q.11 =============================================== #**

In [ ]:
# Q11. Predict the dtype and the sum.

# Output - dtype= float,  sum= 700
# Beacuse pd.to_numeric converts invalid 'NA' value to NaN and other valid values into float

import pandas as pd
df = pd.DataFrame({'price': ['100', '200', 'NA', '400']})
df['price'] = pd.to_numeric(df['price'], errors='coerce')
print(df['price'].dtype)
print(df['price'].sum())

float64
700.0

**# =============================================== Q.12 =============================================== #**

In [ ]:
# Q12. Predict the type of df.loc[0].

# Output - name: 'Rahul' , age: 22 ,  type = Series (1 row of a dataframe)

import pandas as pd
df = pd.DataFrame({'name': ['Rahul', 'Priya'], 'age': [22, 21]})
print(df.loc[0])
print(type(df.loc[0]))

name    Rahul
age        22
Name: 0, dtype: object
<class 'pandas.core.series.Series'>

**# =============================================== Q.13 =============================================== #**

In [ ]:
# Q13. Predict – and explain what's wrong with the modification line.

# Output - there is chained assignment, which gives warning
# So pandas cannot understand whether df_filtered is a copy of df or original df

import pandas as pd
df = pd.DataFrame({'rating': [4.5, 3.8, 4.2, 5.0]})
df_filtered = df[df['rating'] > 4]
df_filtered['rating'] = df_filtered['rating'] * 2   # what warning?
print(df)
print(df_filtered)

   rating
0     4.5
1     3.8
2     4.2
3     5.0
   rating
0     9.0
2     8.4
3    10.0

/tmp/ipykernel_2838/730905810.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['rating'] = df_filtered['rating'] * 2   # what warning?

**# =============================================== Q.14 =============================================== #**

In [ ]:
# Q14. Predict the result AND its dtype. Why is the dtype what it is?

# Output - resukt = 'small, 'small', 9, 16
# dtype= object  -> beacuse there are both str and int

import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3, 4]})
result = df['a'].apply(lambda x: x**2 if x > 2 else 'small')
print(result)
print(result.dtype)

0    small
1    small
2        9
3       16
Name: a, dtype: object
object

**# =============================================== Q.15 =============================================== #**

In [ ]:
# Q15. Predict each output. What's the difference between nunique(), len(unique()), and value_counts()?

# Output - len(df['city'].unique()) = 4 (includes None)
#          df['city'].value_counts() =  Delhi: 2, Mumbai: 1, Bengaluru: 1

import pandas as pd
df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Delhi', 'Bengaluru', None]})
print(df['city'].nunique())
print(len(df['city'].unique()))
print(df['city'].value_counts())

# what i learn -> nunique() counts only UNIQUE NON NULL values (ignores None/NaN)
# So, df['city'].nunique() = 3

3
4
city
Delhi        2
Mumbai       1
Bengaluru    1
Name: count, dtype: int64

**# =============================================== Q.16 =============================================== #**

In [ ]:
# Q16. Predict each line. The commented line will throw an error or silently break — explain why.

# Output - Here is parenthesis issue in that commented line
# because each condition should enclosed in parenthesis while using operators like &

import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3], 'b': [10, 20, 30]})
print(df[df['a'] > 1])

 #print(df[df['a'] > 1 & df['b'] > 15])
 # <-- what's wrong here?

print(df[(df['a'] > 1) & (df['b'] > 15)])

   a   b
1  2  20
2  3  30
   a   b
1  2  20
2  3  30

------------------------------------------------------------------------------------------------------------------------------
**####---------------------------------- Section C – Applied on Indian Startups Dataset   -----------------------------------####**

------------------------------------------------------------------------------------------------------------------------
**## --------------------------------------- Loading & Inspection (Q17 to Q19) -------------------------------------- ##**

**# =============================================== Q.17 =============================================== #**

Q17. After loading the raw CSV (before cleaning), answer:
(a) How many rows and columns?
(b) How many missing values are in each column?
(c) How many exact duplicate rows are present?

In [1]:
# Load the dataset
import pandas as pd

df = pd.read_csv("indian_startups_fundingDADS.csv")

In [2]:
# let's see 1st five rows of dataset
df.head()

,Startup Name,City,INDUSTRY,Funding Stage,Amount,Funding Date,Investors,Founded Year
0,PlayTime Games,DELHI,ecommerce,Series-E,INR 942 Crore,29/02/2024,"Ranjan Pai, Prosus Ventures",2020.0
1,Rebel Foods,ahmedabad,BeautyTech,Pre-A,1440,18/08/2018,Lightspeed,2017.0
2,Freshworks,Kolkata,AgriTech,Pre-Series A,329 Cr,14 Jul 2020,Info Edge,2020.0
3,BigBasket,Mumbai,ecommerce,Series D,₹1405 Cr,31/03/2018,B Capital,2016.0
4,Ola,KOLKATA,EdTech,SERIES E,₹2223 Cr,24-08-2021,Falcon Edge,2017.0

In [3]:
# let's see last five rows of dataset
df.tail()

,Startup Name,City,INDUSTRY,Funding Stage,Amount,Funding Date,Investors,Founded Year
463,Doubtnut,KOLKATA,ecommerce,Seed,88 Cr,09/07/2012,"Elevation Capital, Chiratae Ventures",2010.0
464,EcoMotor,KOLKATA,HealthTech,Seed,₹41 Cr,01-03-2019,"Goldman Sachs, 3one4 Capital, Elevation Capita...",2008.0
465,Zepto,CHENNAI,AI-ML,Bridge,24 Cr,2023/11/24,"Blume Ventures, Inventus Capital",2018.0
466,FastTrack Logistics,KOLKATA,Agri Tech,bridge,INR 700 Crore,08 Dec 2019,"Matrix Partners, Blume Ventures",2018.0
467,Freshworks,Calcutta,fintech,seed,₹468 Cr,NaN,"Norwest Venture, Elevation Capital, Blume Vent...",2016.0

In [4]:
# let's see some information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Startup Name   468 non-null    object
 1   City           468 non-null    object
 2   INDUSTRY       468 non-null    object
 3   Funding Stage  468 non-null    object
 4   Amount         468 non-null    object
 5   Funding Date   449 non-null    object
 6   Investors      458 non-null    object
 7   Founded Year   445 non-null    float64
dtypes: float64(1), object(7)
memory usage: 29.4+ KB

In [5]:
# (a) How many rows and columns?

df.shape
# hence, there are total 468 rows & 8 columns in dataset

(468, 8)

In [6]:
df.isnull()

,Startup Name,City,INDUSTRY,Funding Stage,Amount,Funding Date,Investors,Founded Year
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
463,False,False,False,False,False,False,False,False
464,False,False,False,False,False,False,False,False
465,False,False,False,False,False,False,False,False
466,False,False,False,False,False,False,False,False
467,False,False,False,False,False,True,False,False

In [7]:
# (b) How many missing values are in each column?

df.isnull().sum()

# hence, 19+10+23 = 122 null values

Startup Name      0
City              0
INDUSTRY          0
Funding Stage     0
Amount            0
Funding Date     19
Investors        10
Founded Year     23
dtype: int64

In [8]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
463    False
464    False
465     True
466    False
467    False
Length: 468, dtype: bool

In [9]:
# (c) How many exact duplicate rows are present?

df.duplicated().sum()

# So, there are 18 duplicate rows in dataset

np.int64(18)

**# =============================================== Q.18 =============================================== #**

Q18. After cleaning column names to snake_case, print the cleaned column names sorted
alphabetically. Don't manually type them – use Python on df.columns.

In [11]:
# let's check current column names

df.columns

Index(['Startup Name ', 'City', 'INDUSTRY', 'Funding Stage', 'Amount',
       'Funding Date', 'Investors', 'Founded Year'],
      dtype='object')

In [12]:
# Rename columns to snake_case
# here almost all columns need to rename, so instead rename() use df.columns()

df.columns = [
    "startup_name",
    "city",
    "industry",
    "funding_stage",
    "amount",
    "funding_date",
    "investors",
    "founded_year"
]

# Display updated column names
print(df.columns)

Index(['startup_name', 'city', 'industry', 'funding_stage', 'amount',
       'funding_date', 'investors', 'founded_year'],
      dtype='object')

In [13]:
# .str - applies string operation to every value in column
# .strip() - removes space from start and end of words like ' swiggy' or 'zomato  '
# .title() - make 1st letter capital and remaining lower case

# Clean startup_name
df["startup_name"] = df["startup_name"].str.strip().str.title()

# Clean city
df["city"] = df["city"].str.strip().str.title()

print(df[["startup_name", "city"]].head())

     startup_name       city
0  Playtime Games      Delhi
1     Rebel Foods  Ahmedabad
2      Freshworks    Kolkata
3       Bigbasket     Mumbai
4             Ola    Kolkata

In [14]:
# let's standardize city names

city_mapping = {
    "Bombay": "Mumbai",
    "Bom": "Mumbai",
    "Blr": "Bengaluru",
    "Bangalore": "Bengaluru",
    "Gurgaon": "Gurugram",
    "Ggn": "Gurugram",
    "Delhi": "New Delhi",
    "Calcutta": "Kolkata",
    "Madras": "Chennai",
    "Hyd": "Hyderabad"
}

df["city"] = df["city"].replace(city_mapping)

print(df["city"])   # verify standardized city names

0      New Delhi
1      Ahmedabad
2        Kolkata
3         Mumbai
4        Kolkata
         ...
463      Kolkata
464      Kolkata
465      Chennai
466      Kolkata
467      Kolkata
Name: city, Length: 468, dtype: object

In [15]:
# Let's check what in industry column
print(df["industry"])

0       ecommerce
1      BeautyTech
2        AgriTech
3       ecommerce
4          EdTech
          ...
463     ecommerce
464    HealthTech
465         AI-ML
466     Agri Tech
467       fintech
Name: industry, Length: 468, dtype: object

In [16]:
# Standardize industry names

industry_mapping = {

    "ecommerce": "Ecommerce",      # Ecommerce
    "E-Commerce": "Ecommerce",
    "ECOMMERCE": "Ecommerce",
    "E-commerce": "Ecommerce",

    "SAAS": "SaaS",     # SaaS
    "Saas": "SaaS",
    "saas": "SaaS",

    "Fin-Tech": "FinTech",      # FinTech
    "FINTECH": "FinTech",
    "fintech": "FinTech",
    "Fintech": "FinTech",
    "FT": "FinTech",

    "AI ML": "AI/ML",      # AI/ML
    "AIML": "AI/ML",
    "AI-ML": "AI/ML",

    "Food Tech": "FoodTech",      # FoodTech
    "Food-Tech": "FoodTech",
    "foodtech": "FoodTech",
    "FOOD-TECH": "FoodTech",

    "Health-Tech": "HealthTech",      # HealthTech
    "Health Tech": "HealthTech",
    "healthtech": "HealthTech",
    "HEALTHTECH": "HealthTech",

    "Electric-Vehicles": "Electric Vehicles",      # Electric Vehicles
    "EV": "Electric Vehicles",
    "ev": "Electric Vehicles",

    "PROPTECH": "PropTech",       # PropTech
    "Prop-Tech": "PropTech",

    "Agri Tech": "AgriTech",    # AgriTech
    "Agri-Tech": "AgriTech",
    "agritech": "AgriTech",
    "AGRITECH": "AgriTech",

    "GAMING": "Gaming",     # Gaming
    "gaming": "Gaming",
    "Games": "Gaming",

    "logistics": "Logistics",     # Logistics
    "LOGISTICS": "Logistics",

    "BEAUTYTECH": "BeautyTech",     # BeautyTech
    "Beauty-Tech": "BeautyTech",

    "Edtech": "EdTech",     # EdTech
    "EDTECH": "EdTech",
    "Ed-Tech": "EdTech",

    "Travel-Tech": "TravelTech",    # TravelTech
    "TRAVELTECH": "TravelTech"
}

df["industry"] = df["industry"].replace(industry_mapping)

In [17]:
# Verify standardized industry names
print(df["industry"])

0       Ecommerce
1      BeautyTech
2        AgriTech
3       Ecommerce
4          EdTech
          ...
463     Ecommerce
464    HealthTech
465         AI/ML
466      AgriTech
467       FinTech
Name: industry, Length: 468, dtype: object

In [18]:
# Let's check what in funding_stage column
print(df["funding_stage"])

0          Series-E
1             Pre-A
2      Pre-Series A
3          Series D
4          SERIES E
           ...
463            Seed
464            Seed
465          Bridge
466          bridge
467            seed
Name: funding_stage, Length: 468, dtype: object

In [19]:
# Standardize funding stage names

stage_mapping = {

    # Seed
    "seed": "Seed",
    "SEED": "Seed",

    # Pre-Seed
    "PRE-SEED": "Pre-Seed",
    "Pre Seed": "Pre-Seed",
    "Preseed": "Pre-Seed",

    # Pre-Series A
    "Pre-A": "Pre-Series A",
    "PRE-SERIES A": "Pre-Series A",
    "Pre Series A": "Pre-Series A",

    # Series A
    "SERIES A": "Series A",
    "series a": "Series A",
    "Series-A": "Series A",
    "series_a": "Series A",

    # Series B
    "SERIES B": "Series B",
    "series b": "Series B",
    "Series-B": "Series B",
    "series_b": "Series B",

    # Series C
    "SERIES C": "Series C",
    "series c": "Series C",
    "Series-C": "Series C",

    # Series D
    "SERIES D": "Series D",
    "series d": "Series D",
    "Series-D": "Series D",

    # Series E
    "SERIES E": "Series E",
    "series e": "Series E",
    "Series-E": "Series E",

    # Bridge
    "bridge": "Bridge",
    "BRIDGE": "Bridge",

    # IPO
    "ipo": "IPO"
}

In [20]:
# Replace different funding stage names with standard names

df["funding_stage"] = df["funding_stage"].replace(stage_mapping)
print(df["funding_stage"])

0          Series E
1      Pre-Series A
2      Pre-Series A
3          Series D
4          Series E
           ...
463            Seed
464            Seed
465          Bridge
466          Bridge
467            Seed
Name: funding_stage, Length: 468, dtype: object

In [21]:
print(df["amount"].head(15))

0     INR 942 Crore
1              1440
2            329 Cr
3          ₹1405 Cr
4          ₹2223 Cr
5            ₹65 Cr
6       Undisclosed
7               488
8          ₹2195 Cr
9            295 Cr
10           291 Cr
11          ₹142 Cr
12             3520
13            ₹5 Cr
14            70 Cr
Name: amount, dtype: object

In [22]:
# Remove ₹ symbol
df["amount"] = df["amount"].str.replace("₹", "", regex=False)

# Remove INR
df["amount"] = df["amount"].str.replace("INR", "", regex=False)

# Remove Crore first
df["amount"] = df["amount"].str.replace("Crore", "", regex=False)

# Then remove Cr
df["amount"] = df["amount"].str.replace("Cr", "", regex=False)

# Remove commas
df["amount"] = df["amount"].str.replace(",", "", regex=False)

# Remove extra spaces
df["amount"] = df["amount"].str.strip()

# Convert to numeric
df["amount"] = pd.to_numeric(df["amount"], errors="coerce")

In [23]:
# let's see the result
print(df["amount"].head(15))
print(df["amount"].dtype)

0      942.0
1     1440.0
2      329.0
3     1405.0
4     2223.0
5       65.0
6        NaN
7      488.0
8     2195.0
9      295.0
10     291.0
11     142.0
12    3520.0
13       5.0
14      70.0
Name: amount, dtype: float64
float64

In [24]:
# Convert funding_date column to datetime format
# errors="coerce" converts invalid dates into NaT
# dayfirst=True reads dates in DD-MM-YYYY format

df["funding_date"] = pd.to_datetime(
    df["funding_date"],
    errors="coerce",
    dayfirst=True
)

# Check datatype
print(df["funding_date"].dtype)

datetime64[ns]

In [25]:
# let's remove duplicate rows
df = df.drop_duplicates()

# let's verify duplicate rows
print(df.duplicated().sum())

0

In [26]:
# Now display column names in alphabetical order

print(sorted(df.columns))

['amount', 'city', 'founded_year', 'funding_date', 'funding_stage', 'industry', 'investors', 'startup_name']

**# =============================================== Q.19 =============================================== #**

Q19. Without using .describe(), compute these statistics on the cleaned founded_year column (after
dropping NaN): count, mean, min, max, median, std. Print as a single dictionary with these exact keys.

In [27]:
# Remove missing values like NaN from founded_year column
years = df["founded_year"].dropna()

# Store statistics in a dictionary
stats = {
    "count": years.count(),
    "mean": years.mean(),
    "min": years.min(),
    "max": years.max(),
    "median": years.median(),
    "std": years.std()
}

print(stats)   # Display the dictionary

{'count': np.int64(427), 'mean': np.float64(2016.4285714285713), 'min': 2008.0, 'max': 2022.0, 'median': 2017.0, 'std': 4.246117096325488}

------------------------------------------------------------------------------------------------------------------------
**## --------------------------------------- Cleaning Verification (Q20 to Q24)  -------------------------------------- ##**

**# =============================================== Q.20 =============================================== #**

Q20. After cleaning the city column with the aliases mapped, print all unique city names sorted
alphabetically. There should be exactly 10 cities and no duplicates from case or whitespace.

In [28]:
# get unique city names
df["city"].unique()

array(['New Delhi', 'Ahmedabad', 'Kolkata', 'Mumbai', 'Hyderabad',
       'Noida', 'Pune', 'Bengaluru', 'Chennai', 'Gurugram'], dtype=object)

In [29]:
# let's arrange unique city names in alphabetical order
print(sorted(df['city'].unique()))

['Ahmedabad', 'Bengaluru', 'Chennai', 'Gurugram', 'Hyderabad', 'Kolkata', 'Mumbai', 'New Delhi', 'Noida', 'Pune']

**# =============================================== Q.21 =============================================== #**

Q21. After standardising the industry column using a dict, print the count of startups per industry sorted
from most to least common (use value_counts()).

In [30]:
# let's count number of startups per industry
print(df["industry"].value_counts())

industry
AI/ML                54
FoodTech             39
SaaS                 36
BeautyTech           34
TravelTech           34
Gaming               34
PropTech             32
HealthTech           31
Ecommerce            30
AgriTech             29
Logistics            27
Electric Vehicles    27
FinTech              22
EdTech               21
Name: count, dtype: int64

**# =============================================== Q.22 =============================================== #**

Q22. After converting amount to numeric, print:
(a) The dtype of the column
(b) How many NaN values are there (from 'Undisclosed' entries)
(c) The mean funding amount (ignoring NaN)
(d) The minimum and maximum funding amount

In [31]:
# (a) the dtype of the amount column
print("Datatype of amount column : ", df['amount'].dtype)

Datatype of amount column :  float64

In [32]:
# (b) How many NaN values are there (from 'Undisclosed' entries) in amount column
print("NaN values in amount column : ", df['amount'].isna().sum())

NaN values in amount column :  24

In [33]:
# (c) Mean funding amount (ignoring NaN)
print("Mean funding amount : ", df['amount'].mean())

Mean funding amount :  753.0586854460093

In [34]:
# (d) Minimum and Maximum funding amount
print("Minimum funding amount : ", df['amount'].min())
print("Maximum funding amount : ", df['amount'].max())

Minimum funding amount :  1.0
Maximum funding amount :  3549.0

**# =============================================== Q.23 =============================================== #**

Q23. After converting funding_date to datetime:
(a) Count how many deals happened in each year. Use .dt.year.
(b) Print the year with the highest number of funding deals.

In [35]:
# (a) Count how many deals happened in each year Use .dt.year.

# this counts deals in each year
# and sort them year wise

deals_per_year = df["funding_date"].dt.year.value_counts().sort_index()
print(deals_per_year)

funding_date
2011.0     1
2012.0     1
2013.0     1
2014.0     1
2015.0     3
2016.0     4
2017.0     5
2018.0     5
2019.0     7
2020.0     6
2021.0    14
2022.0    23
2023.0    14
2024.0     7
Name: count, dtype: int64

In [36]:
# (b) Print the year with the highest number of funding deals.

# .idxmax() finds the highest number of deals
print("year with highest funding deals : ", int(deals_per_year.idxmax()))

year with highest funding deals :  2022

**# =============================================== Q.24 =============================================== #**

Q24. After standardising funding_stage, print the count of startups per stage (sorted from most
common to least).

In [37]:
# count number of startups in each funding stage

# value_counts displays the counts be default from largest to lowest
print(df["funding_stage"].value_counts())

funding_stage
Series B        56
Pre-Seed        48
Series E        48
Seed            47
Series C        46
Series A        43
Bridge          41
Series D        38
Pre-Series A    38
IPO             33
Pre-IPO         12
Name: count, dtype: int64

------------------------------------------------------------------------------------------------------------------------
**## -------------------------------------------- Filtering (Q25 to Q28) ------------------------------------------- ##**

**# =============================================== Q.25 =============================================== #**

Q25. Find all Bengaluru-based startups with funding amount > 100 Cr. Print the startup_name and
amount columns, sorted by amount descending.

In [38]:
# find Bengaluru startups with funding amount greater than 100 Cr

bengaluru_startups = df[
    (df["city"] == "Bengaluru") &
    (df["amount"] > 100)
]

# display only startup_name and amount columns
# ort the result by funding amount in descending order

result = bengaluru_startups[
    ["startup_name", "amount"]
].sort_values(by="amount", ascending=False)

print(result)

       startup_name  amount
311        Routemap  3528.0
226     Agriconnect  3526.0
329     Whitehat Jr  3511.0
154        Ecomotor  2244.0
325       Beautybox  2239.0
98           Meesho  2231.0
146       Curefoods  2230.0
26      Mediconnect  2226.0
299     Villagemart  2195.0
236       Vitalcare  1431.0
278           Paytm  1423.0
65        Instaloan  1420.0
252  Playtime Games  1410.0
369            Cred   950.0
67      Simplilearn   923.0
225    Smartscholar   899.0
347         Flyhigh   728.0
447        Agroplus   726.0
291     Agriconnect   713.0
243        Stylehub   705.0
255      Harvestify   497.0
341          Practo   486.0
233       Vitalcare   456.0
88            Zepto   455.0
401        Shopeasy   449.0
149     Mediconnect   304.0
85        Smartshop   214.0
40         Rupaypro   186.0
182         Fetchit   150.0
434       Games24X7   118.0
398         Cuemath   115.0

**# =============================================== Q.26 =============================================== #**

Q26. Using .isin(), find startups whose industry is one of: Fintech, Edtech, HealthTech. Print the total
count.

In [39]:
# filter startups whose industry is FinTech, EdTech or HealthTech

filtered_startups = df[ df["industry"].isin(["FinTech", "EdTech", "HealthTech"]) ]

print("Total startups :", len(filtered_startups))     # Display total count

Total startups : 74

**# =============================================== Q.27 =============================================== #**

Q27. Using .between(), find startups founded between 2015 and 2020 (both inclusive). Print the count.
Be careful – founded_year has missing values.

In [40]:
# instead & operator, use .between() which also reduces length of code
# Filter startups founded between 2015 and 2020 (inclusive)

filtered_startups = df[ df["founded_year"].between(2015, 2020) ]

print("Total startups :", len(filtered_startups))  # Display the total count

Total startups : 211

**# =============================================== Q.28 =============================================== #**

Q28. Using .str.contains() with case=False and na=False, find all startups whose name contains the word
'pay'. Print the unique names.

In [41]:
# let's find startup names containing the word "pay"
# case= False means ignores upper or lower case
# na=False means skips NaN/ missing values

pay_startups = df[ df["startup_name"].str.contains("pay", case=False, na=False) ]

print(pay_startups["startup_name"].unique())   # Display unique startup names

['Rupaypro' 'Razorpay' 'Paytm' 'Paybuddy' 'Quickpay India']

------------------------------------------------------------------------------------------------------------------------
**## ------------------------------------ Transformation & Derived Columns (Q29 to Q32) ------------------------------------ ##**

**# =============================================== Q.29 =============================================== #**

Q29. Add a new column funding_efficiency = amount / (2024 - founded_year). Higher = raised more
capital per year of existence. Sort by funding_efficiency descending. Print top 10 with name, industry,
amount, founded_year, and funding_efficiency.

In [42]:
# let's create a new column first
df["funding_efficiency"] = df["amount"] / (2024 - df["founded_year"])

In [43]:
# let's sort them in descending order
sorted_df = df.sort_values(
    by="funding_efficiency",
    ascending=False
)

In [44]:
# let's display them
print(
    sorted_df[
        [
            "startup_name",
            "industry",
            "amount",
            "founded_year",
            "funding_efficiency"
        ]
    ].head(10)
)

    startup_name           industry  amount  founded_year  funding_efficiency
322   Classroomx              AI/ML  3520.0        2022.0         1760.000000
208     Cropcare          Ecommerce  3518.0        2021.0         1172.666667
123        Nykaa          Logistics  3515.0        2021.0         1171.666667
154     Ecomotor             Gaming  2244.0        2022.0         1122.000000
158   Makemytrip  Electric Vehicles  2202.0        2022.0         1101.000000
55       Blinkit  Electric Vehicles  2196.0        2022.0         1098.000000
246  Fitnessplus            FinTech  3545.0        2020.0          886.250000
171     Stayeasy          Ecommerce  2249.0        2021.0          749.666667
325    Beautybox          Ecommerce  2239.0        2021.0          746.333333
448   Cleanslate  Electric Vehicles  2204.0        2021.0          734.666667

**# =============================================== Q.30 =============================================== #**

Q30. Using .apply() with a lambda, add a funding_tier column based on amount:
amount ≥ 1000 Cr → 'Unicorn'
amount ≥ 500 Cr → 'Mega'
amount ≥ 100 Cr → 'Large'
amount ≥ 10 Cr → 'Mid'
else (including NaN) → 'Small / Unknown'
Print the count of startups in each tier.

In [46]:
# .apply() - applies a function to every value in a column.
# lambda - it is small, anonymous (nameless) function.

# Create funding_tier column based on funding amount
df["funding_tier"] = df["amount"].apply(
    lambda x:
        "Unicorn" if x >= 1000 else
        "Mega" if x >= 500 else
        "Large" if x >= 100 else
        "Mid" if x >= 10 else
        "Small / Unknown"
)

# Count startups in each funding tier
print(df[["amount", "funding_tier"]].head())

   amount funding_tier
0   942.0         Mega
1  1440.0      Unicorn
2   329.0        Large
3  1405.0      Unicorn
4  2223.0      Unicorn

**# =============================================== Q.31 =============================================== #**

Q31. Using pd.cut(), bin founded_year into 3 eras:
Before 2010 → 'Early'
2010 to 2017 → 'Growth'
2018 and later → 'Recent'
Print the count of startups in each era.

In [48]:
# Create era column using pd.cut()
# pd.cut() is used to group continuous numerical values into categories

df["era"] = pd.cut(
    df["founded_year"],                                   # 1st bin will be..,
    bins=[-float("inf"), 2009, 2017, float("inf")],       # -float("inf")= -Infinity to 2009  ..(eveerything before 2010)
    labels=["Early", "Growth", "Recent"]                  # 2nd bin -> 2009 to 2017
)                                                         # 3rd bin -> float("inf") ...2028 to infinity ..(Everythin after 2027)

print(df["era"].value_counts())       # Count startups in each era

era
Recent    207
Growth    195
Early      25
Name: count, dtype: int64

**# =============================================== Q.32 =============================================== #**

Q32. The investors column has multiple investors separated by ', ' (comma + space). Create a new
column investor_count showing the number of investors per startup. Use .apply() with a lambda. Handle
NaN values (count = 0). Print the value_counts() of investor_count.

In [50]:
# Create investor_count column
# using lambda function and .apply(), value_counts
# .split(", ") - splits string into a list
# pd.notna() - check if a value is not missing

df["investor_count"] = df["investors"].apply(
    lambda x: len(x.split(", ")) if pd.notna(x) else 0
)

# Display the count of startups for each investor_count
print(df["investor_count"].value_counts())

investor_count
2    199
3    118
1     94
4     29
0     10
Name: count, dtype: int64

------------------------------------------------------------------------------------------------------------------------
**## --------------------------------------- Aggregation & Grouping (Q33 to Q37)  --------------------------------------- ##**

**# =============================================== Q.33 =============================================== #**

Q33. Compute the average funding amount per industry (ignoring NaN). Sort descending. Print the top 5
industries by average funding.

In [51]:
# Calculate average funding amount for each industry
# df.groupby() - groups similar rows
# .mean() - calculates average
avg_funding = df.groupby("industry")["amount"].mean()

# Sort in descending order
# sort_values() - sort values in descending order
avg_funding = avg_funding.sort_values(ascending=False)

# Display top 5 industries
print(avg_funding.head(5))

industry
FinTech              1217.636364
EdTech               1191.250000
TravelTech           1115.968750
Electric Vehicles    1090.769231
Ecommerce            1035.107143
Name: amount, dtype: float64

**# =============================================== Q.34 =============================================== #**

Q34. For each city, compute three metrics in a single groupby using .agg() with a dictionary:
(a) Number of startups
(b) Total funding raised (sum of amount)
(c) Average funding per startup
Print the top 10 cities by number of startups.

In [52]:
# Compute city-wise startup statistics
# .agg() - performs multiple operations at once in single groupby() operation ...(like sum, mean, count, etc.)

city_stats = df.groupby("city").agg({
    "startup_name": "count",
    "amount": ["sum", "mean"]
})

city_stats.columns = [    # Rename the columns
    "startup_count",
    "total_funding",
    "average_funding"
]

# Sort by startup count in descending order
city_stats = city_stats.sort_values(
    by="startup_count",
    ascending=False
)

print(city_stats.head(10))     # Display top 10 cities

           startup_count  total_funding  average_funding
city
Noida                 62        41499.0       715.500000
Kolkata               51        34029.0       708.937500
Bengaluru             49        39315.0       836.489362
Mumbai                45        32089.0       782.658537
Ahmedabad             44        28250.0       642.045455
Gurugram              44        33275.0       792.261905
Hyderabad             43        29738.0       743.450000
Pune                  42        33333.0       854.692308
Chennai               37        20667.0       558.567568
New Delhi             33        28608.0       953.600000

**# =============================================== Q.35 =============================================== #**

Q35. Interview-style. Which industry has the highest average funding, but only considering industries
with at least 15 startups? (Sparse industries bias the mean.) Print industry name, count, and average
funding.

In [53]:
# Calculate startup count and average funding for each industry
industry_stats = df.groupby("industry").agg({
    "startup_name": "count",
    "amount": "mean"
})

industry_stats.columns = [     # Rename the columns
    "startup_count",
    "average_funding"
]

In [54]:
# Keep only industries with at least 15 startups
industry_stats = industry_stats[  industry_stats["startup_count"] >= 15  ]

# Sort by average funding in descending order
industry_stats = industry_stats.sort_values(
    by="average_funding",
    ascending=False
)

# Display the industry with the highest average funding
print(industry_stats.head(1))

          startup_count  average_funding
industry
FinTech              22      1217.636364

**# =============================================== Q.36 =============================================== #**

Q36. Using pd.crosstab(), show the distribution of funding_tier across the top 5 industries by count.
Rows = industry, columns = funding_tier, values = count of startups.

In [56]:
# pd.crosstab() - this function creates cross-tabulation (freq.table) betn 2 columns
# it shows how many records belongs to each combination of categories

# first find the top 5 industries
top5_industries = df["industry"].value_counts().head(5).index

# keep only those industries
top5_df = df[df["industry"].isin(top5_industries)]

In [59]:
# create the cross-tab
cross_table = pd.crosstab(
    top5_df["industry"],
    top5_df["funding_tier"]
)

print(cross_table)     # display it

funding_tier  Large  Mega  Mid  Small / Unknown  Unicorn
industry
AI/ML            12     7   20                6        9
BeautyTech       14     4    8                2        6
FoodTech         12     5   11                2        9
SaaS             11     4   11                3        7
TravelTech       11     7    4                2       10

**# =============================================== Q.37 =============================================== #**

Q37. For each industry, find the startup with the highest funding amount. Print startup_name, industry,
city, and amount. Hint: groupby + idxmax() on amount.

In [60]:
# Find the index of the startup with the highest funding in each industry
# using groupby() function and .idxmax() function
max_index = df.groupby("industry")["amount"].idxmax()

result = df.loc[max_index, [     # Select those rows
    "startup_name",
    "industry",
    "city",
    "amount"
]]
print(result)

    startup_name           industry       city  amount
322   Classroomx              AI/ML  Ahmedabad  3520.0
195    Boldfoods           AgriTech  Hyderabad  1449.0
93     Vitalcare         BeautyTech       Pune  3522.0
170      Curefit          Ecommerce     Mumbai  3540.0
333    Fitfusion             EdTech     Mumbai  3546.0
118        Paytm  Electric Vehicles       Pune  3533.0
246  Fitnessplus            FinTech  New Delhi  3545.0
21   Simplilearn           FoodTech    Kolkata  3549.0
179    Wealthwiz             Gaming    Kolkata  3549.0
386   Investedge         HealthTech    Kolkata  2219.0
123        Nykaa          Logistics  New Delhi  3515.0
192    Mamaearth           PropTech  Hyderabad  2235.0
56   Whitehat Jr               SaaS  Hyderabad  2250.0
28      Rupaypro         TravelTech  Ahmedabad  3541.0

------------------------------------------------------------------------------------------------------------------------
**## ----------------------------------------- Real Industry Problems (Q38 to Q40)   ----------------------------------------- ##**

**# =============================================== Q.38 =============================================== #**

Q38. Emerging player finder. An 'emerging player' is a startup founded in 2019 or later, with funding ≥
100 Cr, in one of Fintech / Edtech / HealthTech. Find all of them, sort by amount descending, print
name, industry, city, founded_year, and amount. Why might a VC analyst care about this list?

In [61]:
# --- Emerging PLayer Finder --- #

# cond-1 : df["founded_year"] >= 2019
# cond-2 : df["amount"] >= 100
# cond-3 : df["industry"].isin(["FinTech", "EdTech", "HealthTech"])

# combining all these 3 conditions

emerging_players = df[
    (df["founded_year"] >= 2019) &
    (df["amount"] >= 100) &
    (df["industry"].isin(["FinTech", "EdTech", "HealthTech"]))
]

# Sort by funding amount in descending order
emerging_players = emerging_players.sort_values(
    by="amount",
    ascending=False
)

In [62]:
# Display required columns
print(
    emerging_players[
        [
            "startup_name",
            "industry",
            "city",
            "founded_year",
            "amount"
        ]
    ]
)

      startup_name    industry       city  founded_year  amount
246    Fitnessplus     FinTech  New Delhi        2020.0  3545.0
57       Learnlive     FinTech      Noida        2019.0  3512.0
386     Investedge  HealthTech    Kolkata        2020.0  2219.0
178     Classroomx     FinTech      Noida        2022.0  1418.0
269        Vedantu  HealthTech      Noida        2021.0  1413.0
461        Postman      EdTech  Hyderabad        2019.0  1404.0
369           Cred      EdTech  Bengaluru        2020.0   950.0
342        Voltcar      EdTech  Hyderabad        2021.0   916.0
378  Bookmyservice  HealthTech      Noida        2021.0   902.0
417    Villagemart      EdTech   Gurugram        2021.0   896.0
370      Agriboost     FinTech  New Delhi        2021.0   729.0
449      Groomguru  HealthTech      Noida        2021.0   722.0
130      Dermaplus  HealthTech   Gurugram        2019.0   711.0
340       Fundflow     FinTech      Noida        2019.0   709.0
334       Shopeasy     FinTech   Gurugram        2019.0   489.0
290         Zomato  HealthTech   Gurugram        2019.0   322.0
359       Fundflow  HealthTech    Kolkata        2022.0   315.0
11        Rupaypro  HealthTech    Kolkata        2020.0   142.0
25         Flyhigh     FinTech       Pune        2021.0   121.0

In [ ]:
# Why might a VC analyst care about this list ????

# A VC analyst may use this list to identify recently founded startups that have already secured some funding.
# These startups have strong growth potential and may be good candidates for future investment.

**# =============================================== Q.39 =============================================== #**

Q39. Investor hub analysis. A foreign investor wants to know which Indian city has the highest TOTAL
funding raised, considering only cities with at least 20 startups (so the number is meaningful). Print city
name, count, and total funding.

In [63]:
# ----- Investor Hub List ----- #

# Calculate startup count and total funding for each city
city_stats = df.groupby("city").agg({
    "startup_name": "count",
    "amount": "sum"
})

city_stats.columns = [       # Rename the columns
    "startup_count",
    "total_funding"
]

In [64]:
# Keep cities with at least 20 startups
city_stats = city_stats[  city_stats["startup_count"] >= 20  ]

# Sort by total funding in descending order
city_stats = city_stats.sort_values(
    by="total_funding",
    ascending=False
)

# Display the city with the highest total funding
print(city_stats.head(1))

       startup_count  total_funding
city
Noida             62        41499.0

**# =============================================== Q.40 =============================================== #**

Q40. Market saturation. For each combination of (city, industry), count the number of startups. Print the
top 10 most-saturated combinations. This tells a new founder where competition is most intense – and
by elimination, where the gaps might be.

In [65]:
# -------- MARKET SATURATION -------- #

# cond-1 : df.groupby(["city", "industry"])    ...groupby 2 columns
# cond-2 : counr startups ... startup_count
# cond-3 : sort and print top 10

# Count startups for each city and industry combination
market_saturation = df.groupby(
    ["city", "industry"]
).agg({
    "startup_name": "count"
})

market_saturation.columns = ["startup_count"]        # Rename the column

In [66]:
# Sort by startup count in descending order
market_saturation = market_saturation.sort_values(
    by="startup_count",
    ascending=False
)

# Display the top 10 combinations
print(market_saturation.head(10))

                      startup_count
city      industry
Gurugram  FoodTech               10
Bengaluru Gaming                  8
Mumbai    AI/ML                   8
Pune      AI/ML                   8
Ahmedabad AI/ML                   7
Kolkata   AI/ML                   7
          SaaS                    7
Noida     FoodTech                7
          TravelTech              7
Bengaluru AgriTech                7

**# ============================================= THE END  ============================================= #**

**# ============================================ THANK YOU..  ============================================ #**